version: 2
jobs:
  dirs-verify:
    docker:
      - image: golang:1.13.4
        environment:
          GO111MODULE: 'on'
    working_directory: /go/src/github.com/nmiyake/pkg/dirs
    steps:
      - checkout:
          path: /go/src/github.com/nmiyake/pkg
      - run:
          command: go version
      - run:
          command: go env
      - restore_cache:
          name: Restoring Go build cache
          keys:
            - go-build-cache-v1-{{ .Branch }}-{{ .Revision }}
            - go-build-cache-v1-{{ .Branch }}-
            - go-build-cache-v1-
      - restore_cache:
          name: Restoring Go module cache
          keys:
            - go-mod-cache-v1-{{ .Branch }}-{{ .Revision }}-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
            - go-mod-cache-v1-{{ .Branch }}-{{ .Revision }}-{{ checksum "go.mod" }}
            - go-mod-cache-v1-{{ .Branch }}-{{ .Revision }}
            - go-mod-cache-v1-{{ .Branch }}
            - go-mod-cache-v1-
      - restore_cache:
          name: Restoring godel cache
          keys:
            - godel-cache-v1-{{ checksum "godelw" }}-{{ checksum "godel/config/godel.yml" }}
      - run:
          command: ./godelw version
      - save_cache:
          name: Saving godel cache
          key: godel-cache-v1-{{ checksum "godelw" }}-{{ checksum "godel/config/godel.yml" }}
          paths:
            - ~/.godel
      - run:
          command: ./godelw verify --apply=false --skip-test
      - save_cache:
          name: Saving Go module cache
          key: go-mod-cache-v1-{{ .Branch }}-{{ .Revision }}-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
workflows:
  version: 2
  verify-test:
    jobs:
      - dirs-verify
