owner-repo: &owner-repo
  owner-repo: nmiyake/pkg

version: 2.1

orbs:
  go: palantir/go@0.0.14
  godel: palantir/godel@0.0.14

workflows:
  version: 2
  verify-test:
    jobs:
      # dirs
      - godel/verify:
          name: dirs-verify
          checkout-path: /go/src/github.com/nmiyake/pkg/dirs
          executor:
            name: go/golang
            version: 1.13.4
            <<: *owner-repo
      - godel/test:
          name: dirs-test-go-1.13
          checkout-path: /go/src/github.com/nmiyake/pkg/dirs
          executor:
            name: go/golang
            version: 1.13.4
            <<: *owner-repo
      - godel/test:
          name: dirs-test-go-1.12
          checkout-path: /go/src/github.com/nmiyake/pkg/dirs
          executor:
            name: go/golang
            version: 1.12.13
            <<: *owner-repo

      # errorstringer
      - godel/verify:
          name: errorstringer-verify
          checkout-path: /go/src/github.com/nmiyake/pkg/errorstringer
          executor:
            name: go/golang
            version: 1.13.4
            <<: *owner-repo
      - godel/test:
          name: errorstringer-test-go-1.13
          checkout-path: /go/src/github.com/nmiyake/pkg/errorstringer
          executor:
            name: go/golang
            version: 1.13.4
            <<: *owner-repo
      - godel/test:
          name: errorstringer-test-go-1.12
          checkout-path: /go/src/github.com/nmiyake/pkg/errorstringer
          executor:
            name: go/golang
            version: 1.12.13
            <<: *owner-repo

      # gofiles
      - godel/verify:
          name: gofiles-verify
          checkout-path: /go/src/github.com/nmiyake/pkg/gofiles
          executor:
            name: go/golang
            version: 1.13.4
            <<: *owner-repo
      - godel/test:
          name: gofiles-test-go-1.13
          checkout-path: /go/src/github.com/nmiyake/pkg/gofiles
          executor:
            name: go/golang
            version: 1.13.4
            <<: *owner-repo
      - godel/test:
          name: gofiles-test-go-1.12
          checkout-path: /go/src/github.com/nmiyake/pkg/gofiles
          executor:
            name: go/golang
            version: 1.12.13
            <<: *owner-repo
