version: 2.1

orbs:
  go: palantir/go@0.0.12
  godel: palantir/godel@0.0.11

workflows:
  version: 2
  verify-test:
    jobs:
      # dirs
      - godel/verify:
          name: dirs-verify
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: nmiyake/pkg/dirs
      - godel/test:
          name: dirs-test-go-1.13
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: nmiyake/pkg/dirs
      - godel/test:
          name: dirs-test-go-1.12
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: nmiyake/pkg/dirs

      # errorstringer
      - godel/verify:
          name: errorstringer-verify
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: nmiyake/pkg/errorstringer
      - godel/test:
          name: errorstringer-test-go-1.13
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: nmiyake/pkg/errorstringer
      - godel/test:
          name: errorstringer-test-go-1.12
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: nmiyake/pkg/errorstringer

      # gofiles
      - godel/verify:
          name: gofiles-verify
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: nmiyake/pkg/gofiles
      - godel/test:
          name: gofiles-test-go-1.13
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: nmiyake/pkg/gofiles
      - godel/test:
          name: gofiles-test-go-1.12
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: nmiyake/pkg/gofiles
