working_dir: &working_dir
  working_directory: /go/src/github.com/nmiyake/pkg

steps: &steps
  - checkout
  - restore_cache:
      keys:
        - godel-cache-{{ checksum "godelw" }}-{{ checksum "godel/config/godel.yml" }}-v1
  - run: ./godelw version
  - save_cache:
      key: godel-cache-{{ checksum "godelw" }}-{{ checksum "godel/config/godel.yml" }}-v1
      paths:
        - ~/.godel
  - run: echo 'export TESTS_DIR=/tmp/test-results' >> $BASH_ENV
  - run: mkdir -p "${TESTS_DIR}"
  - run: |
         if [ ! -z "$VERIFY" ]; then
           echo "Verify" && ./godelw verify --apply=false --junit-output="$TESTS_DIR/$CIRCLE_PROJECT_REPONAME-tests.xml"
         else
           echo "Test" && ./godelw test --junit-output="$TESTS_DIR/$CIRCLE_PROJECT_REPONAME-tests.xml"
         fi
  - type: test-results-store
    path: /tmp/test-results
  - type: artifacts-store
    path: /tmp/test-results
    destination: test-results

version: 2
jobs:
  go-1.11:
    <<: *working_dir
    environment:
      VERIFY: 1
    docker:
      - image: golang:1.11.2
    steps: *steps
  go-1.10:
    <<: *working_dir
    docker:
      - image: golang:1.10.5
    steps: *steps
  go-1.9:
    <<: *working_dir
    docker:
    - image: golang:1.9.7
    steps: *steps

workflows:
  version: 2
  verify:
    jobs:
      - go-1.11
      - go-1.10
      - go-1.9
